name: Run Interactive Env

services:
  Interactive:
    image: docker.io/infiloop/wfmeta_darshan_util_dxtthread:${TAG:-main}
    working_dir: /workdir
    volumes:
      - ./wfmeta_darshan_workdir:/workdir
    tty: true
    stdin_open: true