name: CI test for PyPerfDump
on:
  push:
    branches:
      - 'pyperfdump'
jobs:
  tests-cmake:
    name: Tests with CMake
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool: [ 'pyperfdump' ]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Setup Requirements for Serial PyPerfDump
      run: |
        sudo sysctl kernel.perf_event_paranoid=-1
        sudo apt update
        sudo apt install  build-essential python3-dev \
                          papi-tools libpapi-dev \
                          libhdf5-dev hdf5-tools
    - name: Build and Test Serial PyPerfDump
      run: |
        cd builds/pyperfdump/
        ./build.sh
        cd ../../tests/pyperfdump/
        ./test.sh
    - name: Change Requirements for Parallel PyPerfDump
      run: |
        sudo apt purge libhdf5-dev hdf5-tools
        sudo apt install  openmpi-bin python3-mpi4py \
                          libhdf5-openmpi-dev hdf5-tools
    - name: Build and Test Parallel PyPerfDump
      run: |
        export PYTHONPATH="/usr/lib/python3/dist-packages:$PYTHONPATH"
        cd builds/pyperfdump/
        ./build.sh
        cd ../../tests/pyperfdump/
        ./test.sh

