name: CI test for PyPerfDump
on:
  push:
    branches:
      - 'pyperfdump'
jobs:
  tests-cmake:
    name: Tests with CMake
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool: [ 'pyperfdump' ]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Setup Requirements for Serial PyPerfDump
      run: |
        sudo sh -c 'echo -1 >/proc/sys/kernel/perf_event_paranoid'
        sudo apt update
        sudo apt install  build-essential python3-dev \
                          papi-tools libpapi-dev \
                          libhdf5-dev hdf5-tools
    - name: Build and Test Serial PyPerfDump
      run: |
        cd builds/pyperfdump/
        git clone https://github.com/RECUP-DOE/pyperfdump.git
        ./build.sh
        cd ../../tests/pyperfdump/
        ./test.sh
        cd ../../builds/pyperfdump
    - name: Setup Requirements for Parallel PyPerfDump
      run: |
        sudo apt purge libhdf5-dev hdf5-tools
        sudo apt install  openmpi-bin python3-mpi4py \
                          libhdf5-openmpi-dev hdf5-tools
    - name: Build and Test Parallel PyPerfDump
      run: |
        ./build.sh
        cd ../../tests/pyperfdump/
        ./test.sh

